### ISSUE TITLE
BatchDownload is not workin

### ISSUE THREAD

**Issue by ShyamKStrand** [wikipathways/wikipathways.org#10]
Dear Concern,

Batch download of pathways from the following link is not working. Could you please help me in downloading.

https://www.wikipathways.org/index.php/Download_All_Pathways

Thanks
Shyam K

**Comment by nunogit** [comment]
Dear Shyam,

Try it now.

The problem should be  solved.

Kind regards,
Nuno

2017-11-02 16:14 GMT+01:00 ShyamKStrand <notifications@github.com>:

**Comment by ShyamKStrand** [comment]
Thanks Nuno, It Worked.

**Comment by AlexanderPico** [comment]
Thanks Nuno!  And Shyam, you might also want to use our newer download option: a documented monthly release that you can more easily cite and reuse. It's highlighted on our Download Page now:
https://www.wikipathways.org/index.php/Download_Pathways

And is archived here:
http://data.wikipathways.org

Now, if you really need downloads of changes made in between these monthly releases, then the links you were using are still the best. But for most use cases, we are recommending the monthly releases instead.
