### ISSUE TITLE
Annotation Panel

### ISSUE THREAD

**Issue by ariutta** [wikipathways/wikipathways.org#101]
Currently wikigenes points to the http URL
http://www.wikigenes.org/e/gene/e/1583.html

It needs to point to the https URL:
https://www.wikigenes.org/e/gene/e/1583.html

**Comment by AlexanderPico** [comment]
That's a BridgeDb issue. Can fix it here:
https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt
