### ISSUE TITLE
Bug when uploading new pathways?

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways.org#102]
Dear all,

 a student of mine (Victor Avramov) tried to upload a new pathway today but was denied - writing access permission or so, he already asked for that.

The strange thing happened when he sent me the gpml file and I uploaded it from my account. The pathway was uploaded correctly, now https://www.wikipathways.org/index.php/Pathway:WP4657, but we typed in a placeholder description (something like "22q11 deletion syndrome" not more...) and when we checked the webpage with the new pathway, the exact description he typed in during his failed attempts to upload appeared there. 
Bug or witchcraft? ;)

Best regards,
Freddie

**Comment by AlexanderPico** [comment]
feature! :D
