### ISSUE TITLE
Missing!? "Mapping Type: Continuous Mapping"

### ISSUE THREAD

**Issue by heartlncrna** [wikipathways/wikipathways.org#103]
I'm trying to color "Fill Color" based on expression profile data. When I use Wikipathways for "Mus musculus" [For example, "Apoptosis" (WP1271), "Toll-like receptor signaling pathway" (WP1271)], "Mapping Type: Continuous Mapping" is not existing. How could I fix this issue?

**Comment by AlexanderPico** [comment]
In the Styles tab in Cytoscape, “continuous” is available for Node Fill Color only when you’ve selected a column that contains continuous values. If you have a columns of names or other string values, then “continuous” will not be shown as an option.
