### ISSUE TITLE
Problems with query for protein interactions and meaning of left and right values in json

### ISSUE THREAD

**Issue by coribushman** [wikipathways/wikipathways.org#104]
I am trying to query wiki pathways for protein interactions given a protein name and in the json tree, the meaning of the values in the left and right fields are unclear. Some of these values are null strings or have a new line in them (such as “Oxidative \nstress”). I have noticed that the majority of the time these values are genes but sometimes they are categories or drugs like “Apoptosis”, “Group object”, or “Tamoxifen”. I wanted to bring these errors to your attention and I am curious to know the meaning of the values in these left and right fields so I can parse the json response body to only get desired gene interactions. Thank you.

**Comment by AlexanderPico** [comment]
https://groups.google.com/d/msgid/wikipathways-discuss/79787C1E-A339-4586-AA59-79018F91BE0C%40gladstone.ucsf.edu?utm_medium=email&utm_source=footer
