### ISSUE TITLE
The mystery of doubled ontologies

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways.org#105]
In some pathways the ontology annotations are doubled. I found that by now in 2 pathways, which are both homology converted
E.g. https://www.wikipathways.org/index.php/Pathway:WP4150 (original: https://www.wikipathways.org/index.php/Pathway:WP3857)

The other one was https://www.wikipathways.org/index.php/Pathway:WP3638 (I thought first that was a mistake and deleted the doubled ontologies) (original pathway https://www.wikipathways.org/index.php/Pathway:WP2371)

**Comment by Chris-Evelo** [comment]
Martina did some fresh homology conversions during the workshop. Maybe you can evaluate that to see whether it is the homology conversion that causes this.
