### ISSUE TITLE
Error in create account

### ISSUE THREAD

**Issue by ibrfakih** [wikipathways/wikipathways.org#111]
Hello I am trying to create a new a
ccount on wikipathways . I received each time an login erroe;: Incorrect or missing confirmation code!!!

**Comment by AlexanderPico** [comment]
What is your WikiPathways username? Did you get a confirmation email?

**Comment by AlexanderPico** [comment]
That message will also appear is you do not answer the challenge question accurately. Try reloading the page and answering a new question.
