### ISSUE TITLE
can't confirm e-mail address

### ISSUE THREAD

**Issue by khermankova** [wikipathways/wikipathways.org#114]
Hi,
I'm trying to finish WikiPathways Academy but unfortunatelly can't recieve confirmation mail. It keeps posting me this:

_Could not send confirmation mail. Check address for invalid characters.

Mailer returned: Failed to send data [SMTP: Invalid response code received from server (code: 554, response: Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-2: noreply@wikipathways.org)]_ 

Any idea what to do?

And is the not verified e-mail adress the reason why I can't create the 'cholesterol pathway' task?
Thank you

**Comment by AlexanderPico** [comment]
Hi. We will be switching to GitHub-managed accounts soon. Currently, we are manually approving new accounts. Can you provide your WikiPathways username and then I can manually approve it.

**Comment by khermankova** [comment]
It's Kherma63,
Thank you

**Comment by AlexanderPico** [comment]
You should be all set! Sorry for the hassle.
