### ISSUE TITLE
classification of wikipathway

### ISSUE THREAD

**Issue by SalvatoreRa** [wikipathways/wikipathways.org#117]
Hi everyone,

I have downloaded the wikipathway, I will use the information for a machine learning model of classification.
I would like to know if there are some categories already done, some clustering of the pathways in some categories, in order to have some ground truth label.

list of pathways that are altered in one disease, some specific categories, metabolic an not, and so on. For example, something similar:

pathway | category  |
apoptosis | cancer |
Vitamin D metabolism | non cancer|

The idea is to have some labels or categories and therefore I can then test the accuracy of the model (or other metrics). 

Thank you for your help

**Comment by AlexanderPico** [comment]
Yes, pathways are annotated with 3 different ontologies: pathway, disease, and cell type. We have made sure that every human pathway is annotated with at least one high-level pathway ontology term.  Many human pathways are also annotated with disease terms, when relevant. Few are annotated with cell terms.

These annotations are in the GPML files you've downloaded. See `bp:openControlledVocabulary` elements. They are also available by web services: https://webservice.wikipathways.org. And by SPARQL: https://sparql.wikipathways.org/. And by R: https://bioconductor.org/packages/release/bioc/html/rWikiPathways.html. 

You can also browse the annotations on our new website, [here](https://new.wikipathways.org/browse/annotations.html) and [here](https://new.wikipathways.org/browse/table.html).
