### ISSUE TITLE
Cache methods for getting 2 new data formats

### ISSUE THREAD

**Issue by ariutta** [wikipathways/wikipathways.org#26]
We need to cache these two calls:
* [the method for getting pvjson (JSON)](https://github.com/wikipathways/wikipathways.org/blob/master/wpi/extensions/Pathways/Pathway.php#L543)
* [the method for getting the SVG used in pvjs](https://github.com/wikipathways/wikipathways.org/blob/master/wpi/extensions/Pathways/Pathway.php#L566) (note we also have another, unrelated way of generating SVG using Batik)

I'm not 100% sure how to do it, but [this looks relevant](https://github.com/wikipathways/wikipathways.org/blob/master/wpi/extensions/Pathways/Pathway.php#L1169).

(These new methods allow us to do some pre-processing for the diagram viewer JS.)

**Comment by AlexanderPico** [comment]
Here's an easy way to check if .json files are being cached in `images` dir. Replace `WP4` with any pathway of interest.

```
cd images
find ./*/*/ -ls | grep "WP4_.*\.json"
```
