### ISSUE TITLE
Critical vulnerability: SearchPathways Special Page

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways.org#27]
Apparently our SearchPathways extension is vulnerable to cross-site scripting. See top "high-confirmed" issue attached. 

I think we just need to restrict the input and escape any potential code submitted into our search fields.
[ws2detail-2018-1-5.pdf](https://github.com/wikipathways/wikipathways.org/files/1608348/ws2detail-2018-1-5.pdf)

**Comment by hexmode** [comment]
I have fixed this on the new site, but I guess I got distracted and
forgot to put it on the live site.
