### ISSUE TITLE
Author list displayed at WikiPathways.org is not revision specific 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/wikipathways.org#3]
Our revision-specific URLs do not show the revision-specific author list at the top of the page, but instead shows the author list of the current version, i.e. the full list. So if an author wants to point to a specific revision with a select author list, this is not possible.

For example, Susan was the original author of WP1403, revision 32834. Here's the URL, showing all authors (see screenshot also):
http://www.wikipathways.org/index.php?title=Pathway:WP1403&oldid=32834

The downloaded gpml correctly shows only Susan as author. So the download URL (http://www.wikipathways.org//wpi/wpi.php?action=downloadFile&type=gpml&pwTitle=Pathway:WP1403&oldid=32834) is correct, but if authors point to the main WP page for the revision, the author list is incorrect. Maybe this is expected? Reporting it in case there is a way to fix it.

![screen shot 2017-09-06 at 3 37 30 pm](https://user-images.githubusercontent.com/1442197/30137686-566b9c0c-9319-11e7-88be-35b8c8642de4.png)

**Comment by AlexanderPico** [comment]
This is rather important as it breaks the concept of using revision-specific links as "pathway publications". We know of one case in particular where the authors who plan to cite and publish a pathway are *expecting* the author list for that version to remain unchanged, even if future authors contribute to future versions.

How hard would this be to fix?

**Comment by AlexanderPico** [comment]
While figuring out the implementation plan for this fix, we might also consider the case where an authors name remains even if all of their contributions are reverted.  This hasn't been raised as an issue by users yet, but clearly it's not right as it currently works.

**Comment by mkutmon** [comment]
Good point. Yes this should be changed. I think the issue with authors who's contributions were reverted is a separate issue. 
@khanspers please ignore the author information in the GPML. That was added manually and was removed by MaintBot in revision 41064. This information should be filled in by WikiPathways automatically in the future but that's a separate issue.

**Comment by hexmode** [comment]
Alexander Pico <notifications@github.com> writes:

> How hard would this be to fix?

Query the DB to find users that made revisions before that point in
time.  To reduce load on the server, the results of this should be
cached in memcached and/or a new db table.

That produces the raw list.

Now, how do you rank them?  The byte size of their contribution?  The
number of connections they make between nodes in a pathway?

About authors whose contributions have been removed:

In the traditional MediaWiki model, you can revert entire revisions
made by an author.  Clearly, if reverts like this were done, we should
ignore the author's contributions.

But what if you overwrite them?  Maybe they're work influenced your
edits -- shouldn't they get credit?

A naive examination of the edits can only ignore the contributions that
were marked as reverted.

Even then, there is some doubt. But people can be trained such that they
understand that if they think the person should get credit, they don't
revert, but overwrite.  If they don't think the person should get
credit, they revert.

**Comment by AlexanderPico** [comment]
Agreed. Reverted edits should not get credit. Overwritten and other scenarios are okay to keep author. I think this approach will solve more problems than it creates.

We already have a short heuristic to determine author order, which I think we should keep:
* author of first upload/create event is always listed first
* all other authors are ranked by number of edits.

These contributions are also revealed by mousing-over the author names on a given pathway. We considered other criteria (like byte size), but decided to keep it simple, since no other approach was fool-proof or clearly better.

**Comment by AlexanderPico** [comment]
Relevant code:
* https://github.com/wikipathways/wikipathways.org/blob/master/wpi/extensions/AuthorInfo/AuthorInfo.php#L137 
* https://github.com/wikipathways/wikipathways.org/blob/master/wpi/extensions/AuthorInfo/AuthorInfo.js

**Comment by khanspers** [comment]
Closing this as it relates to the old site.
