### ISSUE TITLE
WP4172 page is broken, HTTP ERROR 500

### ISSUE THREAD

**Issue by khanspers** [wikipathways/wikipathways.org#34]
The page for WP4172 is completely broken and doesn't load at all, results in a HTTP 500 error:

https://www.wikipathways.org/index.php/Pathway:WP4172

The pathway is PI3K-Akt Signaling Pathway (Homo sapiens), thumbnail is normal.

**Comment by AlexanderPico** [comment]
Might be related to this error in the apache logs:

PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 80 bytes) in /var/www/wikipathways/wpi/extensions/GPMLConverter/GPMLConverter.php on line 146

**Comment by AlexanderPico** [comment]
...which is this line of code:
`
$bridgedbResult = json_decode($bridgedbResultString);
`

So, either a memory leak or perhaps attempting to parse an unexpected (error?) JSON return?

**Comment by ariutta** [comment]
This appears related:

> Warning: proc_open(): fork failed - Cannot allocate memory in /var/www/dev.wikipathways.org/wpi/extensions/GPMLConverter/GPMLConverter.php on line 61

But does that mean it's not even starting the BridgeDb unification?

**Comment by ariutta** [comment]
The error is possibly just in converting GPML to PVJSON, before we even get to BridgeDb unification.

**Comment by ariutta** [comment]
I was able to convert WP4172 from GPML to PVJSON via the command line.

**Comment by khanspers** [comment]
Looks like it works now. Closing.
