### ISSUE TITLE
make the website GDPR compliant

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways.org#62]
The essential things to do are:

- [x] make the Terms of Use clear with what is done with user data (explain what processes we do)
- [ ] allow people to download all their data (User page easy, edits also possible, I guess)
- [ ] allow people to delete their user account (that may be tricky... maybe seek guidance from WMF on that part)

Regarding the user data, this does include IP addresses in Apache log files. And it also covers anything involving cookies, e.g. of trackers. (The law has many aspects, but it seems doable...)

I mark this as bug, as we are violating European law at this moment... that makes this a bit urgent, actually... easiest solution (purely hypothetical :) is to close access from EU countries :)

**Comment by egonw** [comment]
The processing of user data that I can think of right now (keep in mind this central rule: "any processing that has not been reported and approved by all users is *not* allowed"):

1. use website usage for website for overall, anonymous statistics (Apache Logs)
2. use website usage for website for Google Analytics
3. use website usage for website for server maintenance
4. use Account info for authorisation and authentication (including cookies)
5. use Account info for to report author information on pathways web pages
6. use Account info for to report author information in data releases as CCZero

Points 4-6 probably need to indicate what account info is used.

**Comment by nunogit** [comment]
We need to make a page with the terms of usage and privacy aspects. There we should state if we interact with other services where user data is provided.

**Comment by AlexanderPico** [comment]
This should be easy enough. Want to draft an updated terms?  

I agree that edits are clearly NOT personal data; and apache logs and google analytics are all anonymous.  Downloading "personal" data is simply their user page, which is already doable. 

We already support deletion of accounts as well. We will NOT remove authors from the history of pathway edits.

**Comment by egonw** [comment]
I'd love to... but I wont' have time for the before the first week of July, I'm afraid...

Thanks for providing already some further detail about our processes, because that is essential to this law...

**Comment by nunogit** [comment]
Just a 5 cent question. If you contribute to something and that something is CC0, is that something still yours?

**Comment by hexmode** [comment]
There is no owner under CC0 because (as much as possible) the IP is
public domain.

https://wiki.creativecommons.org/wiki/CC0_FAQ

**Comment by AlexanderPico** [comment]
And from another perspective, it is “still yours” since you are a member of the public. It’s just not exclusively yours. A major point of public domain and CC0 is that no one else can come along and claim that it’s exclusively theirs and deny you access to it.

**Comment by DeniseSl22** [comment]
Check out the terms of service from proteopedia, see:
http://proteopedia.org/wiki/index.php/Proteopedia:Terms_of_Service

**Comment by egonw** [comment]
I've added an initial section. It is not by far enough to comply to the GDPR law, and we still have to make that full list:

```
* '''EU General Data Protection Regulation''' - we value your privacy and commit ourselves full to the European GDPR, which requires, among other things, that we are 100% transparent in how we use your data. When you visit this website, there are various ways we "get" data. For example, by design, we learn your IP address. If you create an account, the information you provide you agreed to allow us to share that (the wiki concept). We do not share your data with third parties, other than the data files we provide as download and on our webpages. We use Google Analytics as a third party service to help us develop this project. A detailed page is being prepared. Questions are most welcome via email.
```

**Comment by egonw** [comment]
@hexmode, are you aware of any MediaWiki efforts to make MW wikis GDPR compliant by default? E.g. by implementing the requirement that users can easily download all their info (profile page + all edits), or so?

**Comment by egonw** [comment]
With the move to GitHub, GDPR compliance becomes easier: we piggyback on the GitHub implementation.
