### ISSUE TITLE
Output for "No annotated interactions" include visible HTML [vm1]

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways.org#63]
For example on [WP2199](https://vm1.wikipathways.org/Pathway:WP2199):

![image](https://user-images.githubusercontent.com/26721/41465225-85fa5a82-709d-11e8-8fec-be2064e68b4d.png)

**Comment by hexmode** [comment]
See wikipathways/wikipathways-upgrade-2017#32
