### ISSUE TITLE
Ontology tags do not show up (yet) [vm1]

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways.org#64]
For example in [WP2199](https://vm1.wikipathways.org/Pathway:WP2199):

![image](https://user-images.githubusercontent.com/26721/41465292-bd424b8a-709d-11e8-9c30-d0f7fa3f1d56.png)

**Comment by hexmode** [comment]
This is being handled in wikipathways/wikipathways-upgrade-2017#8
