### ISSUE TITLE
API get list by text does not return info

### ISSUE THREAD

**Issue by mohmhm1** [wikipathways/wikipathways.org#78]
The web service api findPathwaysByText does not yield a JSON object anymore.

The example call from your site

https://webservice.wikipathways.org/findPathwaysByText?query=apoptosis

will render a blank page.

Thanks

**Comment by mkutmon** [comment]
Thanks for reporting. Looks like our indexer didn't start up correctly after an unplanned power outage yesterday. I'll have a look at it asap.

**Comment by egonw** [comment]
@mkutmon, let's make a test for our website monitor for that too then...

**Comment by egonw** [comment]
@mkutmon, it seems you fixed it, right?

**Comment by mkutmon** [comment]
I restarted the indexer and search works again.

**Comment by mohmhm1** [comment]
Hi. Thanks for updating. Seems the calls still yield blank pages.

**Comment by AlexanderPico** [comment]
Sorry for the unfortunate timing. We had two controlled power outages on campus. The last one was completed an hour ago or so. So once I or someone on the team has a chance to repeat the steps performed by Tina, it should be working again. 

 - Alex

**Comment by AlexanderPico** [comment]
OK. It's up again and working. And we don't have any more power outages planned.

**Comment by mohmhm1** [comment]
Awesome! Works! Thanks
