### ISSUE TITLE
Last modified date in PW download != last modified date

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/wikipathways.org#8]
Hi guys,

When I downloaded a [PW](http://www.wikipathways.org/index.php/Pathway:WP1422) for a presentation as a PDF, I noticed that the "Last modified date" does not add up with the date on which the last changes have been made.  I don't know if this problem is related to Pathvisio or WikiPathways, but since I downloaded the PW from the website, I report the issue in this repository.
Could this be a bug?

**Comment by mkutmon** [comment]
PathVisio doesn't fill this field. So it was manually set by someone. I think we should remove this field from all pathways - @AlexanderPico what do you think?

**Comment by AlexanderPico** [comment]
100% agree. It's an old field from the GenMAPP days; it should be removed.

**Comment by DeniseSl22** [comment]
This also related to several PWs showing the licence under the PW title (for example: CC 2.0 licence); this is only visible when I download the GPML and edit it in Pathvisio. I think this has to be removed as well right?

**Comment by AlexanderPico** [comment]
Yup, not a bug. I try to remove all these fields whenever you see them. Personally, I'd like to get rid of this old info element altogether...
