### ISSUE TITLE
Create "Rare diseases" portal

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways.org#85]
For the EJP-RD project we need (soon) a seperate portal for rare disease pathways which is at the moment a sub-part of the disease portal.
The Rare disease portal should get the logos from EJP-RD, Elixir, and Rett Expertise Centre and contain the pathways which are now in the rare disease and Blau book sub-portals. 

If you (Kristina?) would create the page and give me editing rights (I have them already for the disease portal so maybe I already have them for all) and help a bit (you are using quite some templates I have not seen yet) that would be great!

**Comment by egonw** [comment]
@fehrhart, I am not sure what you mean with "subportal". Why not just https://www.wikipathways.org/index.php/Portal:RareDisease ?

**Comment by Chris-Evelo** [comment]
Yes, I think that is what is should be. Plus we should have a URL: https://raredisease.wikipathways.org since we do not want portal web addresses to be php. The subportal idea only means that there should be a link on the "disease" portal to the "rare disease" portal

**Comment by egonw** [comment]
As soon as we have the content of that portal "ready", then we can ask Alex to create the subdomain.

**Comment by fehrhart** [comment]
done

**Comment by egonw** [comment]
@AlexanderPico, can you please create the https://raredisease.wikipathways.org subdomain and have it point to https://www.wikipathways.org/index.php/Portal:RareDisease ?

**Comment by AlexanderPico** [comment]
done!

**Comment by egonw** [comment]
Thanks! It has not propagated to my device yet, but it should be available around the world somewhere during the day.

**Comment by Chris-Evelo** [comment]
Thanks! The http version works for me the https version not yet.

It was well received at the EJP RD meeting BTW

**Comment by egonw** [comment]
@AlexanderPico, is there a simple explanation http:// works but https:// redirects to the vocabulary webpage?

**Comment by egonw** [comment]
Ah, right, https:// also doesn't work for aop.wikipathways.org.
