### ISSUE TITLE
Migrate off JNLP for PathVisio

### ISSUE THREAD

**Issue by Artoria2e5** [wikipathways/wikipathways.org#87]
Java 10+ or something made Java Web Start completely unusuable, and Java 8 has ceased receiving public support from Oracle. It might be a good idea to start exploring other ways to run PathVisio (which, well, does not officially support Java 10+) and trying out other compatible editors. (How do I try out pvjs, by the way?)

One thing to be immediately done is add an entry about installing an older Java and setting it to open JNLP in https://www.wikipathways.org/index.php/Help:Known_problems. Multiple versions of Java can coexist.

PS: Ubuntu/OpenJDK should be able to work with JNLP with `icedtea-web` installed. Considering changing that one, as Ubuntu has officially abandoned Oracle JVM  in the repo.

**Comment by AlexanderPico** [comment]
Great suggetions. I believe the current development plan is to bundle Java together with PathVisio using a proper installer, like install4j. This will release users from having to think about their other Java installations. We could then register .gpml files to open in PV and skip the whole .jnlp situation.  We are considering skipping Java 9 and 10, which are not LTS and going from 8 to 11.

Re: pvjs, we have implemented [PathwayWidets](https://www.wikipathways.org/index.php/PathwayWidget) that you can embed into sites without having to touch pvjs code. However, if you *really* want to touch the code, it's [here](https://github.com/wikipathways/pvjs), but its directly implementation not supported by our small team. It's well documented, but not well tested outside of our particular use case. You're on your own! :)

**Comment by Artoria2e5** [comment]
Great! Going local is a good approach, and it feels more transparent too.

As one of the Linux distribution-side people, I do have some minor pet peeves about bundling an entire JVM (or any other supposedly "system" library). I guess it won't be a big problem though: we can write our own launcher scripts and use your beautiful gpml file icons anyway.

* * *

PS: [`icedtea-web`](http://icedtea.wildebeest.org/download/icedtea-web-binaries/) does work with newer Javas, including Java 11. It could be still useful for the PathVisio upstream, but not really for WikiPathyway anymore. Well if you want to force-feed PV to Java 11 for a test I guess it's a good tool for that job.
