### ISSUE TITLE
text encoding issue

### ISSUE THREAD

**Issue by need47** [wikipathways/wikipathways.org#91]
Dear team,

For this (and some other pathways): https://www.wikipathways.org/index.php/Pathway:WP534, there might be some text encoding issue in the description field, i.e. CH3COCOOâˆ’ .

Glycolysis is the metabolic pathway that converts glucose C6H12O6, into pyruvate, CH3COCOOâˆ’ + H+. The free energy released in this process is used to form the ATP and NADH.
Gluconeogenesis is a metabolic pathway that results in the generation of glucose from non-carbohydrate carbon substrates such as pyruvate, lactate, glycerol, glucogenic amino acids, and fatty acids.

Description adapted from Wikipedia.

Please consider to fix it. Thank you.

**Comment by need47** [comment]
The issue also exists in the downloaded .gpml file.

**Comment by khanspers** [comment]
Hi,

Thanks for letting us know. I fixed the problem so the description is now correct on the page and the gpml is updated as well.

Regards,

Kristina

Kristina Hanspers
WikiPathways Admin
wikipathways.org

**Comment by need47** [comment]
Thanks for the prompt fix. I hope this is a site-wide fix because there are other pathways with same issue. Please also fix the bulk down gpml files. Thanks.
