### ISSUE TITLE
Download error visualisation

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/wikipathways.org#92]
Just got an error when trying to download a Gene list (.txt) file from a pathway.
I tried for several PWs, some work, some don't (so I don't think that is necessarily a problem of the server move).

However, I got the following error message:
![image](https://user-images.githubusercontent.com/26277832/56270859-71909480-60f7-11e9-80a1-1965fe13444c.png)

I wasn't logged in, which I tried to do (it took very long before the login page was displayed btw...).
When I then returned to the page I previously visited, I got the following:

![image](https://user-images.githubusercontent.com/26277832/56270946-a0a70600-60f7-11e9-88d1-2e90401f4053.png)

Again, I'm not sure if this is due to the switch of servers, just wanted to mention it.

**Comment by AlexanderPico** [comment]
Correct. This is the same on the old server. We've had this bug for years... Not prioritized to fix since we've been focused on the upgrade site. And in particular, this has been fixed on the upgrade site.
