### ISSUE TITLE
Download gene lists not working

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/wikipathways.org#93]
For several pathways, I cannot download the gene list (.txt). There are some I found which it does work for, but also there the results are not what I would expect... See example:
![image](https://user-images.githubusercontent.com/26277832/56271428-cbde2500-60f8-11e9-8608-12cf191f1384.png)

Several IDs are not for genes, so why is it called a GeneList then?... the PW can be found here: https://www.wikipathways.org/index.php/Pathway:WP2636 .

**Comment by AlexanderPico** [comment]
This should be tested and reported on the new upgrade site. It should be working there (as designed). If you want to change the gene list specs (or name) then suggest changes there. I don't think we have any devs still working on the old site code at this point.
