### ISSUE TITLE
Unified login for wikimedia projects

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/wikipathways.org#94]
I was going through some Wikidata documentation, and I found this page: https://meta.wikimedia.org/wiki/Help:Unified_login . It would be great if we could implement this in the new wikimedia website as well. Perhaps it would be easier then to see which authors on pathway pages of Wikipedia we could invite to create a PW for WikiPathways (for example), or check the level of knowledge from contributors (meaning if you have edited lots of stuff on Wikipedia and Wikidata, you can probably also learn how to do that for WPs).

Not high priority, just wanted to mention it here.

**Comment by AlexanderPico** [comment]
Another great suggestion, but this is wrong repo and issue tracker. Please post suggestions for dev on the new site here:  https://github.com/wikipathways/wikipathways-upgrade-2017/issues

I'm not sure anyone will be looking at this old repo :)
