### ISSUE TITLE
Download of Reactome pathways denied 

### ISSUE THREAD

**Issue by fehrhart** [wikipathways/wikipathways.org#98]
Download of the Reactome pathway collection from https://www.pathvisio.org/downloads/download-pathways/ does not work. I get this error:
'''Unable process download:''' zip I/O error: Permission denied
zip error: Could not create output file (/var/www/wikipathways/wpi/cache/wikipathways_Homo_sapiens_Curation-Reactome_Approved__gpml.zip)

**Comment by AlexanderPico** [comment]
fixed permissions. Link works now.
